name: livecheck

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  livecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: Bump
        uses: Homebrew/actions/bump-packages@main
        with:
          token: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
          formulae: godot
